[upstream]
purl = 'pkg:generic/linux?url=https://kernel.org/releases.json&regex=linux-(\d+\.\d+(?:\.\d+)?)\.tar\.xz'

[[source]]
key = "default"
url = "https://cdn.kernel.org/pub/linux/kernel/v{major}.x/linux-{version}.tar.xz"
hash = "sha256-8JeHxPMBWcX3rjYN9lYkAarpWnyqvDckH+AsUABoxzM="

[pin]
version = "7.2.4"
date = "2026-09-06"
