# the shell hook is generated by the binary itself, so there is nothing to install beside it
{ package, pkgs }:
package {
  name = "direnv";
  # it execs the shell and keeps a unix-only environment model
  platforms.posix = true;
  uses = [ "go" ];
  go.packages = [ "." ];
  # direnv runs every .envrc through bash, and with no path compiled in it takes whatever
  # `bash` the caller's PATH has, so the same .envrc behaves differently per host
  # (GNUmakefile BASH_PATH, internal/cmd/config.go). `version` needs nothing here, it is
  # //go:embed version.txt.
  go.ldflags = [ "-X main.bashPath=${pkgs.bash}/bin/bash" ];
  dependencies = [ pkgs.bash ];
  tests.version = "version";
}
